"""add job_status table

Revision ID: ba163e7dcc15
Revises: 2aeebc52aaae
Create Date: 2026-07-13 14:27:45.128828
"""
from alembic import op
import sqlalchemy as sa

import app.database


# revision identifiers, used by Alembic.
revision = 'ba163e7dcc15'
down_revision = '2aeebc52aaae'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_status',
    sa.Column('job_name', sa.String(), nullable=False),
    sa.Column('last_success_at', app.database.UTCDateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('job_name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job_status')
    # ### end Alembic commands ###
