"""initial schema

Revision ID: ee08ba069158
Revises: 
Create Date: 2026-07-04 23:55:36.183833
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee08ba069158'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apod',
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('explanation', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('hdurl', sa.String(), nullable=True),
    sa.Column('media_type', sa.String(), nullable=False),
    sa.Column('copyright', sa.String(), nullable=True),
    sa.Column('thumbnail_url', sa.String(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('date')
    )
    op.create_table('iss_passes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pass_type', sa.String(), nullable=False),
    sa.Column('observer_lat', sa.Float(), nullable=False),
    sa.Column('observer_lng', sa.Float(), nullable=False),
    sa.Column('observer_alt', sa.Float(), nullable=False),
    sa.Column('passes_json', sa.String(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("pass_type IN ('visual','radio')", name='ck_iss_pass_type'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pass_type', 'observer_lat', 'observer_lng', 'observer_alt', name='uq_iss_passes')
    )
    op.create_table('iss_position_batch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('positions', sa.String(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('iss_tle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tle_line0', sa.String(), nullable=False),
    sa.Column('tle_line1', sa.String(), nullable=False),
    sa.Column('tle_line2', sa.String(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('launches',
    sa.Column('ll2_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('net', sa.DateTime(), nullable=False),
    sa.Column('status_abbrev', sa.String(), nullable=False),
    sa.Column('status_name', sa.String(), nullable=False),
    sa.Column('agency_name', sa.String(), nullable=False),
    sa.Column('agency_type', sa.String(), nullable=True),
    sa.Column('rocket_name', sa.String(), nullable=False),
    sa.Column('rocket_family', sa.String(), nullable=True),
    sa.Column('mission_name', sa.String(), nullable=True),
    sa.Column('mission_description', sa.String(length=2000), nullable=True),
    sa.Column('mission_type', sa.String(), nullable=True),
    sa.Column('pad_name', sa.String(), nullable=False),
    sa.Column('pad_location', sa.String(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('livestream_urls', sa.String(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('ll2_id')
    )
    with op.batch_alter_table('launches', schema=None) as batch_op:
        batch_op.create_index('ix_launches_agency_name', ['agency_name'], unique=False)
        batch_op.create_index('ix_launches_net', ['net'], unique=False)

    op.create_table('login_attempts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('identifier', sa.String(), nullable=False),
    sa.Column('ip_address', sa.String(), nullable=False),
    sa.Column('failed_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('login_attempts', schema=None) as batch_op:
        batch_op.create_index('ix_login_attempts_identifier_ip_failed_at', ['identifier', 'ip_address', 'failed_at'], unique=False)

    op.create_table('mars_photo',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('sol', sa.Integer(), nullable=False),
    sa.Column('earth_date', sa.String(), nullable=False),
    sa.Column('rover_name', sa.String(), nullable=False),
    sa.Column('camera_name', sa.String(), nullable=False),
    sa.Column('img_src', sa.String(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rover_name', 'sol', 'camera_name', 'id', name='uq_mars_photo_composite')
    )
    op.create_table('n2yo_quota',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('window_start', sa.DateTime(), nullable=False),
    sa.Column('used', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('neo',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('close_approach_date', sa.String(), nullable=False),
    sa.Column('absolute_magnitude_h', sa.Float(), nullable=True),
    sa.Column('estimated_diameter_min_km', sa.Float(), nullable=True),
    sa.Column('estimated_diameter_max_km', sa.Float(), nullable=True),
    sa.Column('is_potentially_hazardous', sa.Boolean(), nullable=False),
    sa.Column('relative_velocity_kph', sa.Float(), nullable=True),
    sa.Column('miss_distance_km', sa.Float(), nullable=True),
    sa.Column('orbiting_body', sa.String(), nullable=True),
    sa.Column('nasa_jpl_url', sa.String(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('neo', schema=None) as batch_op:
        batch_op.create_index('ix_neo_close_approach_date', ['close_approach_date'], unique=False)

    op.create_table('space_weather_event',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('start_date', sa.String(), nullable=False),
    sa.Column('raw_json', sa.String(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("event_type IN ('FLR','GST','RBE','SEP','CME')", name='ck_space_weather_event_type'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('space_weather_event', schema=None) as batch_op:
        batch_op.create_index('ix_space_weather_event_type_start_date', ['event_type', 'start_date'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('phone_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('email IS NOT NULL OR phone IS NOT NULL', name='ck_users_email_or_phone'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('notification_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ll2_id', sa.String(), nullable=False),
    sa.Column('change_type', sa.String(), nullable=False),
    sa.Column('channel', sa.String(), nullable=False),
    sa.Column('delivery_status', sa.String(), nullable=False),
    sa.Column('error_detail', sa.String(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("channel IN ('email','sms')", name='ck_notification_log_channel'),
    sa.CheckConstraint("delivery_status IN ('sent','failed')", name='ck_notification_log_delivery_status'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notification_log', schema=None) as batch_op:
        batch_op.create_index('ix_notification_log_user_sent_at', ['user_id', 'sent_at'], unique=False)

    op.create_table('otps',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(), nullable=False),
    sa.Column('code_hash', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('failed_attempts', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("channel IN ('email','phone')", name='ck_otps_channel'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('otps', schema=None) as batch_op:
        batch_op.create_index('ix_otps_user_channel_created', ['user_id', 'channel', 'created_at'], unique=False)

    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.create_index('ix_refresh_tokens_token_hash', ['token_hash'], unique=False)
        batch_op.create_index('ix_refresh_tokens_user_revoked', ['user_id', 'revoked'], unique=False)

    op.create_table('subscriptions',
    sa.Column('id', sa.String(), server_default=sa.text('(lower(hex(randomblob(16))))'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('ll2_id', sa.String(), nullable=True),
    sa.Column('agency_name', sa.String(), nullable=True),
    sa.Column('notify_email', sa.Boolean(), nullable=False),
    sa.Column('notify_sms', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("type IN ('launch','agency')", name='ck_subscription_type'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'type', 'agency_name', name='uq_subscription_agency'),
    sa.UniqueConstraint('user_id', 'type', 'll2_id', name='uq_subscription_launch')
    )
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.create_index('ix_subscriptions_agency_name', ['agency_name'], unique=False)
        batch_op.create_index('ix_subscriptions_user_id', ['user_id'], unique=False)

    op.create_table('pending_notifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('subscription_id', sa.String(), nullable=False),
    sa.Column('ll2_id', sa.String(), nullable=False),
    sa.Column('change_type', sa.String(), nullable=False),
    sa.Column('old_value', sa.String(), nullable=True),
    sa.Column('new_value', sa.String(), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("change_type IN ('NET_SLIP','STATUS_CHANGE','NEW_LAUNCH')", name='ck_pending_notifications_change_type'),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pending_notifications', schema=None) as batch_op:
        batch_op.create_index('ix_pending_notifications_attempts_created', ['attempt_count', 'created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pending_notifications', schema=None) as batch_op:
        batch_op.drop_index('ix_pending_notifications_attempts_created')

    op.drop_table('pending_notifications')
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_index('ix_subscriptions_user_id')
        batch_op.drop_index('ix_subscriptions_agency_name')

    op.drop_table('subscriptions')
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.drop_index('ix_refresh_tokens_user_revoked')
        batch_op.drop_index('ix_refresh_tokens_token_hash')

    op.drop_table('refresh_tokens')
    with op.batch_alter_table('otps', schema=None) as batch_op:
        batch_op.drop_index('ix_otps_user_channel_created')

    op.drop_table('otps')
    with op.batch_alter_table('notification_log', schema=None) as batch_op:
        batch_op.drop_index('ix_notification_log_user_sent_at')

    op.drop_table('notification_log')
    op.drop_table('users')
    with op.batch_alter_table('space_weather_event', schema=None) as batch_op:
        batch_op.drop_index('ix_space_weather_event_type_start_date')

    op.drop_table('space_weather_event')
    with op.batch_alter_table('neo', schema=None) as batch_op:
        batch_op.drop_index('ix_neo_close_approach_date')

    op.drop_table('neo')
    op.drop_table('n2yo_quota')
    op.drop_table('mars_photo')
    with op.batch_alter_table('login_attempts', schema=None) as batch_op:
        batch_op.drop_index('ix_login_attempts_identifier_ip_failed_at')

    op.drop_table('login_attempts')
    with op.batch_alter_table('launches', schema=None) as batch_op:
        batch_op.drop_index('ix_launches_net')
        batch_op.drop_index('ix_launches_agency_name')

    op.drop_table('launches')
    op.drop_table('iss_tle')
    op.drop_table('iss_position_batch')
    op.drop_table('iss_passes')
    op.drop_table('apod')
    # ### end Alembic commands ###
